// var admin = require("firebase-admin");

// var serviceAccount = require("./project1-382f0-firebase-adminsdk-86u87-f28182538e.json");

// admin.initializeApp({
//   credential: admin.credential.cert(serviceAccount),
//   databaseURL: "https://project1-382f0-default-rtdb.asia-southeast1.firebasedatabase.app"
// });




// // Import Admin SDK
// const { getDatabase } = require('firebase-admin/database');

// // Get a database reference to our blog
// const db = getDatabase();
// const ref = db.ref('server/saving-data/fireblog');




// const usersRef = ref.child('users');
// usersRef.set({
//   hari: {
//     date_of_birth: 'June 23, 1912',
//     full_name: 'hari krishnan'
//   },
//   febin: {
//     date_of_birth: 'December 9, 1906',
//     full_name: 'febin mathew'
//   }
// });









// usersRef.child('hari').set({
//     date_of_birth: 'June 23, 1912',
//     full_name: 'hari krishnan'
//   });
//   usersRef.child('febin').set({
//     date_of_birth: 'December 9, 1906',
//     full_name: 'febin mathew'
//   }); 
  
  
  
  
//   const hopperRef = usersRef.child('febin');
//   hopperRef.update({
//     'nickname': 'choki'
//   });
  
  
  
  
//   usersRef.update({
//     'hari/nickname': 'kola',
//     'febin/nickname': 'chokki'
//   });
  
  
  
  
  
//   // usersRef.update({
//   //   'hari': {
//   //     'nickname': 'kola'
//   //   },
//   //   'febin': {
//   //     'nickname': 'choki'
//   //   }
//   // });
  
  
//   // userRef.update('I\'m writing data', (error) => {
//   //   if (error) {
//   //     console.log('Data could not be saved.' + error);
//   //   } else {
//   //     console.log('Data saved successfully.');
//   //   }
//   // }); 
  
  
  
//   usersRef.push(
//   {
//     "posts": {
//       "0": {
//         "author": "gracehop",
//         "title": "Announcing COBOL, a New Programming Language"
//       },
//       "1": {
//         "author": "alanisawesome",
//         "title": "The Turing Machine"
//       }
//     }
//   })
  
  
  
  
//   const newPostRef = usersRef.push();
//   newPostRef.set({
//     author: 'gracehop',
//     title: 'Announcing COBOL, a New Programming Language'
//   });
  
//   // we can also chain the two calls together
//   usersRef.push().set({
//     author: 'alanisawesome',
//     title: 'The Turing Machine'
//   });
  
  
  
//   // This is equivalent to the calls to push().set(...) above
//   usersRef.push({
//     author: 'gracehop',
//     title: 'Announcing COBOL, a New Programming Language'
//   });;
  
  
  
//   // Generate a reference to a new location and add some data using push()
//   const newPostRef1 = usersRef.push();
  
//   // Get the unique key generated by push()
//   const postId = newPostRef1.key;
//   console.log(postId)
  
  
//   const upvotesRef = db.ref('server/saving-data/fireblog/posts/-JRHTHaIs-jNPLXOQivY/upvotes');
//   upvotesRef.transaction((current_value) => {
//     return (current_value || 0) + 1;
//   });
  
  
  
  
//   // Attach an asynchronous callback to read the data at our posts reference
//   ref.on('value', (snapshot) => {
//     console.log(snapshot.val());
//   }, (errorObject) => {
//     console.log('The read failed: ' + errorObject.name);
//   }); 
  
  
  
//   // Retrieve new posts as they are added to our database
//   ref.on('child_added', (snapshot, prevChildKey) => {
//     const newPost = snapshot.val();
//     console.log('Author: ' + newPost.author);
//     console.log('Title: ' + newPost.title);
//     console.log('Previous Post ID: ' + prevChildKey);
//   });
  
  
  
//   // Get the data on a post that has changed
//   ref.on('child_changed', (snapshot) => {
//     const changedPost = snapshot.val();
//     console.log('The updated post title is ' + changedPost.title);
//   });
  
  
  
//   // Get a reference to our posts
//   const ref1 = db.ref('server/saving-data/fireblog/posts');
  
//   // Get the data on a post that has been removed
//   ref1.on('child_removed', (snapshot) => {
//     const deletedPost = snapshot.val();
//     console.log('The blog post titled \'' + deletedPost.title + '\' has been deleted');
//   });
  
  
  
  
//   let count = 0;
  
//   ref.on('child_added', (snap) => {
//     count++;
//     console.log('added:', snap.key);
//   });
  
//   // length will always equal count, since snap.val() will include every child_added event
//   // triggered before this point
//   ref.once('value', (snap) => {
//     console.log('initial data loaded!', snap.numChildren() === count);
//   });